FROM debian

ADD debian.list /etc/apt/sources.list.d/


RUN apt-get update && apt-get -y upgrade && apt -y install nginx && apt-get clean && \
    cd /var/www/ && rm -rf ./* && \
    mkdir -p Poqx.com/img && \
    chmod -R 754 /var/www/Poqx.com/ && \
    useradd Andrey && groupadd Pakin && usermod -a -G Pakin Andrey && \
    chown -R Andrey:Pakin /var/www/Poqx.com && \
    sed -i 's$/var/www/html$/var/www/Poqx.com$g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user Andrey/g' /etc/nginx/nginx.conf
	
ADD index.html /var/www/Poqx.com/
ADD img.jpg /var/www/Poqx.com/img/
CMD ["nginx", "-g", "daemon off;"]